environment         = "challenge"
service_name        = "woogie-bucket"
project_env         = "dev"
applications        = "woogie-bucket-challenge-dev"
route53_domain_name = "userleap.de-vi.me"
route53_record_name = "app.userleap.de-vi.me"
