environment              = "challenge"
service_name             = "woogie-bucket"
project_env              = "dev"
region                   = "us-east-1"
account_id               = "262667049843"
elb_account_id           = "127311923021"
state_bucket_name        = "tfstate-userleap-us-east-1-bucket"
dynamodb_lock_table_name = "userleap-tfstate-lock-db"
