key_pair_name       = "devi-us-west-1"
route53_domain_name = "userleap.de-vi.me"
route53_record_name = "app.userleap.de-vi.me"
ecs_image_id        = "262667049843.dkr.ecr.us-west-1.amazonaws.com/userleap"
ecs_image_version   = "react"